/*******************************************************************************
 *                                O P E N  T S
 *******************************************************************************
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2025 Electronic Arts Inc.
 * Copyright 2026 OpenTS contributors
 *
 * Contains material derived from Electronic Arts source code.
 * Modified by OpenTS contributors, 2026.
 * EA's GPLv3 Section 7 additional terms and supplemental warranty
 * disclaimers apply; see LICENSE.md.
 ******************************************************************************/

/***********************************************************************************************
 ***              C O N F I D E N T I A L  ---  W E S T W O O D  S T U D I O S               ***
 ***********************************************************************************************
 *                                                                                             *
 *                 Project Name : Command & Conquer                                            *
 *                                                                                             *
 *                     $Archive:: /G/wwlib/wwfont.h                                           $*
 *                                                                                             *
 *                      $Author:: Scott_b                                                     $*
 *                                                                                             *
 *                     $Modtime:: 4/21/00 1:03p                                               $*
 *                                                                                             *
 *                    $Revision:: 3                                                           $*
 *                                                                                             *
 *---------------------------------------------------------------------------------------------*
 * Functions:                                                                                  *
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

#pragma once

#include "font.h"
#include "surface.h"

class ConvertClass;

/*
**	This is a concrete font class object that is used to handle font data as generated by
**	the legacy FONTMAKE.EXE utility.
*/
class WWFontClass : public FontClass
{
		typedef FontClass BASECLASS;

	public:
		WWFontClass(void const * fontdata, bool isoutlined=false, int shadow=0, int scale=1);
		virtual ~WWFontClass(void) override {}

		void *Set_Font_Data(void const * fontdata)
		{
			void *old = (void *) FontData;
			FontData = (FontType *)fontdata;
			return(old);
		}

		void *Get_Font_Data(void)  {
			return((void *)FontData);
		}

		using FontClass::Char_Pixel_Width;
		virtual int Char_Pixel_Width(char32_t code) const override;
		virtual int String_Pixel_Width(char const * string) const override;
		virtual void String_Pixel_Bounds(const char * string, Rect & bounds) const override;
		virtual int Get_Width(void) const override;
		virtual int Get_Height(void) const override;
		virtual int Get_Scale(void) const override {return(Scale);}
		virtual Point2D Print(char const * string, Surface & surface, Rect const & cliprect, Point2D const & point, ConvertClass const & converter, unsigned char const * remap=NULL) const override;

		virtual int Set_XSpacing(int x) override;
		virtual int Set_YSpacing(int y) override;

	private:

		/*
		**	Is the font an outline type font (with special outline
		**	pixels in the source art)?
		*/
		bool IsOutlinedData;

		/*
		**	Shadow type to use when displaying this font. The value only applies if the
		**	font is equipped with outline data.
		*/
		int Shadow;

		/*
		**	Override font X spacing value.
		*/
		int FontXSpacing;

		/*
		**	Override font Y spacing value.
		*/
		int FontYSpacing;

		// Pixels this font's glyphs carry per classic pixel.
		int Scale;

		/*
		**	Header structure of the font data file.
		*/
		struct FontType {
			unsigned short FontLength;
			unsigned char FontCompress;
			unsigned char FontDataBlocks;
			unsigned short InfoBlockOffset;
			unsigned short OffsetBlockOffset;
			unsigned short WidthBlockOffset;
			unsigned short DataBlockOffset;
			unsigned short HeightOffset;
		};
		FontType const * FontData;

		// Whether the glyphs follow Windows-1252 rather than code page 437.
		bool IsWindows1252;

		int Raw_Width(void) const;
		int Raw_Height(void) const;
		int Glyph_Count(void) const;
		unsigned char Glyph_Index(char32_t code) const;
};
